version: 2

jobs:
  # for unit test
  build_test:
    docker:
      - image: circleci/python:3.6.3-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest --html=pytest-report/report.html
      - store_artifacts:
          path: pytest-report/
          destination: tr1
  api_testing:
    docker:
      - image: circleci/python:3.6.3-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt 
      - run:
          name: Spin up api application
          command: |
            . venv/bin/activate
            make app
          background: true
          environment:
            FLASK_APP: src/api/app.py
            FLASK_RUN_PORT: 5000
      - run: sleep 3
      - run:
          name: Run Api Acceptance tests
          command: |
            . venv/bin/activate
            behave src/api/features/
  ui_testing:
    docker:
      - image: circleci/python:3.6.3-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Spin up api application
          command: |
            . venv/bin/activate
            make app
          background: true
          environment:
            FLASK_APP: src/api/app.py
            FLASK_RUN_PORT: 5000
      - run: 
            name: Spin up web application
            command: |
              . venv/bin/activate
              make app-web
            background: true
            environment:
              FLASK_APP: src/web/app.py
              FLASK_RUN_PORT: 5001
      - run: sleep 3
      - run:
          name: Run Acceptance UI Testse
          command: make test-e2e


workflows:
    version: 2
    continues_testing_workflow:
      jobs:
        - build_test
        - api_testing:
            requires:
              - "build_test"
        - ui_testing:
            requires:
                - "build_test"
