version: 2

jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.3-jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest --html=pytest-report/report.html
      - store_artifacts:
          path: pytest-report/
          destination: tr1
      

workflows:
    version: 2
    continues_testing_workflow:
      jobs:
        - build_test
    