version: 2
jobs:
  build:
    working_directory: ~/heracles
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          FLASK_APP: api/app.py
          FLASK_RUN_PORT: 8050 
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest --html=pytest-report/report.html
      - run:
          name: Spin up the application
          command: |
            . venv/bin/activate
            flask run
          background: true
      - run: sleep 5
      - run:
          name: Run Api Acceptance tests
          command: |
            . venv/bin/activate
            behave api/features/
      - store_artifacts:
          path: pytest-report/
          destination: tr1
      - store_test_results:
          path: pytest-report/
      
             
