---
resources:
  - name: app
    type: git
    source:
      uri: https://github.com/pjcalvo/full-ct-cycle.git
      branch: master

jobs:
  - name: build-and-test
    public: true
    serial: true
    plan:
      - get: app
        trigger: true
      - task: setup
        config:
          inputs:
            - name: app
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          run:
            dir: app
            path: ci/scripts/setup.sh
      - task: unit-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app
          outputs:
            - name: venv
          run:
            dir: app
            path: ci/scripts/unit-tests.sh
      - task: integration-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app
            - name: venv
              path: app/venv
          run:
            dir: app
            path: ci/scripts/integration-tests.sh