---
resources:
  - name: full-ct-cycle
    type: git
    source:
      uri: https://github.com/pjcalvo/full-ct-cycle.git
      branch: master
  - name: docker-python
    type: docker-image
    source:
      repository: python

jobs:
  - name: build-and-test
    serial: true
    plan:
      - get: full-ct-cycle
      - get: docker-python
      - task: setup
        config:
          platform: linux
          inputs:
            - docker-python
          run:
            path: ci/scripts/setup.sh
      - task:
        config:
          platform: linux
          inputs:
            - docker-python
          run:
            path: ci/scripts/unit-tests.sh


  