---
resources:
  - name: app
    type: git
    source:
      uri: https://github.com/pjcalvo/full-ct-cycle.git
      branch: master

jobs:
  - name: build-and-test
    public: true
    serial: true
    plan:
      - get: app
        trigger: true
      - task: setup
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app
          run:
            path: app/ci/scripts/setup.sh   
      - task: unit-test
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app
          run:
            path: app/ci/scripts/unit-tests.sh
      - task: build-app
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app
          run:
            path: app/ci/scripts/build.sh

      - task: integration-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app
          run:
            path: app/ci/scripts/integration-tests.sh