---
platform: linux

resources:
  - name: app
    type: git
    source:
      uri: https://github.com/pjcalvo/full-ct-cycle.git
      branch: master


jobs:
  - name: build-and-test
    public: true
    serial: true
    plan:
      - get: app
        trigger: true
      - task: setup
        config:
          inputs:
            - name: app
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          run:
            path: app/ci/scripts/setup.sh   
          outputs: 
            - name: app/venv
      - task: unit-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: app/venv
          run:
            path: app/ci/scripts/unit-tests.sh
      # - task: build-app
      #   config:
      #     platform: linux
      #     inputs:
      #       - name: code
      #     run:
      #       path: app/ci/scripts/build.sh

      # - task: integration-tests
      #   config:
      #     platform: linux
      #     inputs:
      #       - name: code
      #     run:
      #       path: app/ci/scripts/integration-tests.sh