---
resources:
  - name: full-ct-cycle
    type: git
    source:
      uri: https://github.com/pjcalvo/full-ct-cycle.git
      branch: master

jobs:
  - name: build-and-test
    public: true
    serial: true
    plan:
      - get: full-ct-cycle
      - task: setup
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: python}

          inputs:
            - name: full-ct-cycle

          run:
            path: ci/scripts/setup.sh
      
      - task: unit-test
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: python}

          inputs:
            - name: full-ct-cycle

          run:
            path: ci/scripts/unit-tests.sh


  